# Generated by Django 5.1.1 on 2024-10-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SignInInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sup_name', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=50)),
                ('company_addr', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='MedReg',
            fields=[
                ('supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supply_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('unit_price', models.IntegerField()),
                ('num_units', models.IntegerField()),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms_project.supplier')),
            ],
        ),
    ]
