# Generated by Django 5.1.1 on 2024-10-17 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medconsume',
            fields=[
                ('supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supply_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('unit_price', models.IntegerField()),
                ('num_units', models.IntegerField()),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms_project.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Medequip',
            fields=[
                ('supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supply_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('unit_price', models.IntegerField()),
                ('num_units', models.IntegerField()),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms_project.supplier')),
            ],
        ),
    ]
