# Generated by Django 5.1.1 on 2024-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='login_info',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login_info',
            old_name='Username',
            new_name='username',
        ),
    ]
