# Generated by Django 5.1.1 on 2024-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0002_medconsume_medequip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medequip',
            name='num_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medequip',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
