# Generated by Django 5.1.1 on 2024-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0003_user_details_delete_signin_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='confirm_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
