# Generated by Django 5.1.1 on 2024-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0003_alter_medequip_num_units_alter_medequip_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medconsume',
            name='num_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medconsume',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medreg',
            name='num_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medreg',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
