# Generated by Django 5.1.1 on 2024-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0004_alter_login_info_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.CharField(max_length=45),
        ),
    ]
