# Generated by Django 5.1.1 on 2024-10-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0005_alter_user_details_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='signin_info',
        ),
    ]
