# Generated by Django 5.1.1 on 2024-10-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
