# Generated by Django 5.1.1 on 2024-10-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0007_log_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin_info',
        ),
    ]
