# Generated by Django 5.1.1 on 2024-10-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0009_signin_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SignInInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='log_out',
        ),
        migrations.DeleteModel(
            name='login_info',
        ),
        migrations.DeleteModel(
            name='signin_info',
        ),
    ]
