# Generated by Django 5.1.1 on 2024-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0010_logininfo_signininfo_delete_log_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedReg',
            fields=[
                ('supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supply_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('unit_price', models.IntegerField()),
                ('num_units', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
            ],
        ),
    ]
